### PR TITLE
Update Chinese Localisation

### PR DESCRIPTION
**Pull request by LunarTraveller**
Ver 2024.9.16
Thank you for updating this great mod Retro.

### CODE REVIEW

**Comment by openly-retro** [comment]
> Ver 2024.9.16 Thank you for updating this great mod Retro.

Hello LunarTraveller!

I am very grateful for your efforts and for your work. Thank you very much for the translation.

I would like to mention your name or your translation group on the Steam workshop page of the mod.

How would you like to be mentioned / credited?

**Comment by openly-retro** [comment]
Hi @LunarTraveller , I have reviewed the changes. I greatly appreciate your time.

I see that `localisation/simp_chinese/rikk_mdlc_l_simp_chinese_extended_machines.yml` was deleted, but where is the new file?

It would be very nice to have translations for `rikk_mdlc_l_simp_chinese_extended_machines.yml`, if you have some time. Thank you 🙏🏽

**Comment by LunarTraveller** [comment]
Sorry, we have missed this file. It will be made up in a day or two and merged into this PR.
As for credit, please write "Doves Localization".
And here is our workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=2131014154
Thanks.

**Comment by LunarTraveller** [comment]
Added the missing file and renamed english to simp_chinese.
Since we use a translation site, the export format may differ from the source file. :P

**Pull request merged**
